export const SET_NAVBARINDEX = 'SET_NAVBARINDEX';
export const SET_STORENAVBARINDEX = 'SET_STORENAVBARINDEX';
export const SET_DRAWERTOPNAVBAR = 'SET_DRAWERTOPNAVBAR';
export const SET_USERLOADING = 'SET_USERLOADING';

// User
export const SET_USER = 'SET_USER';
export const SET_USER_SIGNOUT = 'SET_USER_SIGNOUT';
export const SET_USER_CART = 'SET_USER_CART';
export const DELETE_USER_CART = 'DELETE_USER_CART';
export const CLEAR_USER_CARTS = 'CLEAR_USER_CARTS';
export const UPDATE_BILL = 'UPDATE_BILL';

// UserCart
export const ADD_STOREITEM_CART = 'ADD_STOREITEM_CART';
export const DELETE_STOREITEM_CART = 'DELETE_STOREITEM_CART';
export const ADD_ONLINEITEM_CART = 'ADD_ONLINEITEM_CART';
export const DELETE_ONLINEITEM_CART = 'DELETE_ONLINEITEM_CART';

// Products
export const SET_STOREPRODUCTCATALOGS = 'SET_STOREPRODUCTCATALOGS';
export const SET_ONLINEPRODUCTCATALOGS = 'SET_ONLINEPRODUCTCATALOGS';
